const DATA = [
  {
    no: 1,
    IDa: "123456",
    IDk: "1098283",
    tgl: "24/10/23",
    nm: "Asep Sutrisno",
    div: "Web Design",
    stat: <span className="blue-tag">Izin</span>,
    alasan: "Mau ke ragunan",
  },
  {
    no: 2,
    IDa: "123456",
    IDk: "1098283",
    tgl: "24/10/23",
    nm: "Asep Sutrisno",
    div: "Web Design",
    stat: <span className="blue-tag">Sakit</span>,
    alasan: "Mau ke ragunan",
  },
  {
    no: 3,
    IDa: "123456",
    IDk: "1098283",
    tgl: "24/10/23",
    nm: "Asep Sutrisno",
    div: "Web Design",
    stat: <span className="blue-tag">Izin</span>,
    alasan: "Mau ke ragunan",
  },
  {
    no: 4,
    IDa: "123456",
    IDk: "1098283",
    tgl: "24/10/23",
    nm: "Asep Sutrisno",
    div: "Web Design",
    stat: <span className="blue-tag">Sakit</span>,
    alasan: "Mau ke ragunan",
  },
  {
    no: 5,
    IDa: "123456",
    IDk: "1098283",
    tgl: "24/10/23",
    nm: "Asep Sutrisno",
    div: "Web Design",
    stat: <span className="blue-tag">Sakit</span>,
    alasan: "Mau ke ragunan",
  },
  {
    no: 6,
    IDa: "123456",
    IDk: "1098283",
    tgl: "24/10/23",
    nm: "Asep Sutrisno",
    div: "Web Design",
    stat: <span className="blue-tag">Izin</span>,
    alasan: "Mau ke ragunan",
  },
  {
    no: 7,
    IDa: "123456",
    IDk: "1098283",
    tgl: "24/10/23",
    nm: "Asep Sutrisno",
    div: "Web Design",
    stat: <span className="blue-tag">Izin</span>,
    alasan: "Mau ke ragunan",
  },
  {
    no: 8,
    IDa: "123456",
    IDk: "1098283",
    tgl: "24/10/23",
    nm: "Asep Sutrisno",
    div: "Web Design",
    stat: <span className="blue-tag">Izin</span>,
    alasan: "Mau ke ragunan",
  },
  {
    no: 9,
    IDa: "123456",
    IDk: "1098283",
    tgl: "24/10/23",
    nm: "Asep Sutrisno",
    div: "Web Design",
    stat: <span className="blue-tag">Izin</span>,
    alasan: "Mau ke ragunan",
  },
  {
    no: 10,
    IDa: "123456",
    IDk: "1098283",
    tgl: "24/10/23",
    nm: "Asep Sutrisno",
    div: "Web Design",
    stat: <span className="blue-tag">Izin</span>,
    alasan: "Mau ke ragunan",
  },
  {
    no: 11,
    IDa: "123456",
    IDk: "1098283",
    tgl: "24/10/23",
    nm: "Asep Sutrisno",
    div: "Web Design",
    stat: <span className="blue-tag">Izin</span>,
    alasan: "Mau ke ragunan",
  },
  {
    no: 12,
    IDa: "123456",
    IDk: "1098283",
    tgl: "24/10/23",
    nm: "Asep Sutrisno",
    div: "Web Design",
    stat: <span className="blue-tag">Izin</span>,
    alasan: "Mau ke ragunan",
  },
  {
    no: 13,
    IDa: "123456",
    IDk: "1098283",
    tgl: "24/10/23",
    nm: "Asep Sutrisno",
    div: "Web Design",
    stat: <span className="blue-tag">Izin</span>,
    alasan: "Mau ke ragunan",
  },
  {
    no: 14,
    IDa: "123456",
    IDk: "1098283",
    tgl: "24/10/23",
    nm: "Asep Sutrisno",
    div: "Web Design",
    stat: <span className="blue-tag">Izin</span>,
    alasan: "Mau ke ragunan",
  },
];

export default DATA;
