const DATA = [
  {
    no: 1,
    IDa: "123456",
    IDk: "1098283",
    tgl: "24/10/23",
    nm: "Asep Sutrisno",
    div: "Web Design",
    stat_i: <span className="blue-tag">Izin</span>,
    shift: <span className="blue-tag">Pagi</span>,
    alasan: "Mau ke ragunan",
    jm: "07.30",
    stat_p: <span className="green-tag">Tepat Waktu</span>,
    jk: "05.01",
  },
  {
    no: 2,
    IDa: "123456",
    IDk: "1098283",
    tgl: "24/10/23",
    nm: "Asep Sutrisno",
    div: "Web Design",
    stat_i: <span className="blue-tag">Sakit</span>,
    shift: <span className="blue-tag">Siang</span>,
    alasan: "Mau ke ragunan",
    jm: "08.30",
    stat_p: <span className="red-tag">Terlambat</span>,
    jk: "05.01",
  },
  {
    no: 3,
    IDa: "123456",
    IDk: "1098283",
    tgl: "24/10/23",
    nm: "Asep Sutrisno",
    div: "Web Design",
    stat_i: <span className="blue-tag">Izin</span>,
    shift: <span className="blue-tag">Pagi</span>,
    alasan: "Mau ke ragunan",
    jm: "07.30",
    stat_p: <span className="green-tag">Tepat Waktu</span>,
    jk: "05.01",
  },
  {
    no: 4,
    IDa: "123456",
    IDk: "1098283",
    tgl: "24/10/23",
    nm: "Asep Sutrisno",
    div: "Web Design",
    stat_i: <span className="blue-tag">Sakit</span>,
    shift: <span className="blue-tag">Siang</span>,
    alasan: "Mau ke ragunan",
    jm: "07.30",
    stat_p: <span className="green-tag">Tepat Waktu</span>,
    jk: "05.01",
  },
  {
    no: 5,
    IDa: "123456",
    IDk: "1098283",
    tgl: "24/10/23",
    nm: "Asep Sutrisno",
    div: "Web Design",
    stat_i: <span className="blue-tag">Sakit</span>,
    shift: <span className="blue-tag">Pagi</span>,
    alasan: "Mau ke ragunan",
    jm: "08.30",
    stat_p: <span className="red-tag">Terlambat</span>,
    jk: "05.01",
  },
  {
    no: 6,
    IDa: "123456",
    IDk: "1098283",
    tgl: "24/10/23",
    nm: "Asep Sutrisno",
    div: "Web Design",
    stat_i: <span className="blue-tag">Izin</span>,
    shift: <span className="blue-tag">Pagi</span>,
    alasan: "Mau ke ragunan",
    jm: "07.30",
    stat_p: <span className="green-tag">Tepat Waktu</span>,
    jk: "05.01",
  },
  {
    no: 7,
    IDa: "123456",
    IDk: "1098283",
    tgl: "24/10/23",
    nm: "Asep Sutrisno",
    div: "Web Design",
    stat_i: <span className="blue-tag">Izin</span>,
    shift: <span className="blue-tag">Pagi</span>,
    alasan: "Mau ke ragunan",
    jm: "08.30",
    stat_p: <span className="red-tag">Terlambat</span>,
    jk: "05.01",
  },
  {
    no: 8,
    IDa: "123456",
    IDk: "1098283",
    tgl: "24/10/23",
    nm: "Asep Sutrisno",
    div: "Web Design",
    stat_i: <span className="blue-tag">Izin</span>,
    shift: <span className="blue-tag">Siang</span>,
    alasan: "Mau ke ragunan",
    jm: "07.30",
    stat_p: <span className="green-tag">Tepat Waktu</span>,
    jk: "05.01",
  },
  {
    no: 9,
    IDa: "123456",
    IDk: "1098283",
    tgl: "24/10/23",
    nm: "Asep Sutrisno",
    div: "Web Design",
    stat_i: <span className="blue-tag">Izin</span>,
    shift: <span className="blue-tag">Pagi</span>,
    alasan: "Mau ke ragunan",
    jm: "08.30",
    stat_p: <span className="red-tag">Terlambat</span>,
    jk: "05.01",
  },
  {
    no: 10,
    IDa: "123456",
    IDk: "1098283",
    tgl: "24/10/23",
    nm: "Asep Sutrisno",
    div: "Web Design",
    stat_i: <span className="blue-tag">Izin</span>,
    shift: <span className="blue-tag">Siang</span>,
    alasan: "Mau ke ragunan",
    jm: "07.30",
    stat_p: <span className="green-tag">Tepat Waktu</span>,
    jk: "05.01",
  },
  {
    no: 11,
    IDa: "123456",
    IDk: "1098283",
    tgl: "24/10/23",
    nm: "Asep Sutrisno",
    div: "Web Design",
    stat_i: <span className="blue-tag">Izin</span>,
    shift: <span className="blue-tag">Pagi</span>,
    alasan: "Mau ke ragunan",
    jm: "08.30",
    stat_p: <span className="red-tag">Terlambat</span>,
    jk: "05.01",
  },
  {
    no: 12,
    IDa: "123456",
    IDk: "1098283",
    tgl: "24/10/23",
    nm: "Asep Sutrisno",
    div: "Web Design",
    stat_i: <span className="blue-tag">Izin</span>,
    shift: <span className="blue-tag">Siang</span>,
    alasan: "Mau ke ragunan",
    jm: "07.30",
    stat_p: <span className="green-tag">Tepat Waktu</span>,
    jk: "05.01",
  },
  {
    no: 13,
    IDa: "123456",
    IDk: "1098283",
    tgl: "24/10/23",
    nm: "Asep Sutrisno",
    div: "Web Design",
    stat_i: <span className="blue-tag">Izin</span>,
    shift: <span className="blue-tag">Siang</span>,
    alasan: "Mau ke ragunan",
    jm: "07.30",
    stat_p: <span className="green-tag">Tepat Waktu</span>,
    jk: "05.01",
  },
  {
    no: 14,
    IDa: "123456",
    IDk: "1098283",
    tgl: "24/10/23",
    nm: "Asep Sutrisno",
    div: "Web Design",
    stat_i: <span className="blue-tag">Izin</span>,
    shift: <span className="blue-tag">Pagi</span>,
    alasan: "Mau ke ragunan",
    jm: "07.30",
    stat_p: <span className="green-tag">Tepat Waktu</span>,
    jk: "05.01",
  },
];

export default DATA;
