const DATA = [
  { ID: 1, Nama: "John Doe", Divisi: "IT", "Asal Kampus": "Universitas ABC" },
  {
    ID: 2,
    Nama: "Jane Doe",
    Divisi: "Marketing",
    "Asal Kampus": "Universitas XYZ",
  },
  { ID: 1, Nama: "John Doe", Divisi: "IT", "Asal Kampus": "Universitas ABC" },
  {
    ID: 2,
    Nama: "Jane Doe",
    Divisi: "Marketing",
    "Asal Kampus": "Universitas XYZ",
  },
  { ID: 1, Nama: "John Doe", Divisi: "IT", "Asal Kampus": "Universitas ABC" },
  {
    ID: 2,
    Nama: "Jane Doe",
    Divisi: "Marketing",
    "Asal Kampus": "Universitas XYZ",
  },
  { ID: 1, Nama: "John Doe", Divisi: "IT", "Asal Kampus": "Universitas ABC" },
  {
    ID: 2,
    Nama: "Jane Doe",
    Divisi: "Marketing",
    "Asal Kampus": "Universitas XYZ",
  },
  { ID: 1, Nama: "John Doe", Divisi: "IT", "Asal Kampus": "Universitas ABC" },
  {
    ID: 2,
    Nama: "Jane Doe",
    Divisi: "Marketing",
    "Asal Kampus": "Universitas XYZ",
  },
  { ID: 1, Nama: "John Doe", Divisi: "IT", "Asal Kampus": "Universitas ABC" },
  {
    ID: 2,
    Nama: "Jane Doe",
    Divisi: "Marketing",
    "Asal Kampus": "Universitas XYZ",
  },
  { ID: 1, Nama: "John Doe", Divisi: "IT", "Asal Kampus": "Universitas ABC" },
  {
    ID: 2,
    Nama: "Jane Doe",
    Divisi: "Marketing",
    "Asal Kampus": "Universitas XYZ",
  },
  { ID: 1, Nama: "John Doe", Divisi: "IT", "Asal Kampus": "Universitas ABC" },
  {
    ID: 2,
    Nama: "Jane Doe",
    Divisi: "Marketing",
    "Asal Kampus": "Universitas XYZ",
  },
  { ID: 1, Nama: "John Doe", Divisi: "IT", "Asal Kampus": "Universitas ABC" },
  {
    ID: 2,
    Nama: "Jane Doe",
    Divisi: "Marketing",
    "Asal Kampus": "Universitas XYZ",
  },
  { ID: 1, Nama: "John Doe", Divisi: "IT", "Asal Kampus": "Universitas ABC" },
  {
    ID: 2,
    Nama: "Jane Doe",
    Divisi: "Marketing",
    "Asal Kampus": "Universitas XYZ",
  },
  { ID: 1, Nama: "John Doe", Divisi: "IT", "Asal Kampus": "Universitas ABC" },
  {
    ID: 2,
    Nama: "Jane Doe",
    Divisi: "Marketing",
    "Asal Kampus": "Universitas XYZ",
  },
  { ID: 1, Nama: "John Doe", Divisi: "IT", "Asal Kampus": "Universitas ABC" },
  {
    ID: 2,
    Nama: "Jane Doe",
    Divisi: "Marketing",
    "Asal Kampus": "Universitas XYZ",
  },
  { ID: 1, Nama: "John Doe", Divisi: "IT", "Asal Kampus": "Universitas ABC" },
  {
    ID: 2,
    Nama: "Jane Doe",
    Divisi: "Marketing",
    "Asal Kampus": "Universitas XYZ",
  },
];

export default DATA;
